---
title: "data_cleaning"
author: "Ethan"
date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


### Reading Raw Data

```{r libraries_raw, message=FALSE, warning=FALSE}

library(readxl)
library(sf)
library(janitor)
library(readr)
library(tidyverse)
library(raster)
library(units)

df_raw <- read_excel("data/2021_01_06_Climate Vulnerability Composite Score_MASTER FILE.xlsx", 
    sheet = "Composite (exp+vul) score", 
    col_types = c("text", "numeric", "numeric", 
        "numeric", "skip", "numeric", "numeric", 
        "skip", "skip", "skip", "skip", "skip", 
        "skip"))


exposure_raw <- read_excel("data/2021_01_06_Climate Vulnerability Composite Score_MASTER FILE.xlsx", 
    sheet = "Composite (exposure only)", 
    col_types = c("text", "skip", "numeric", 
        "numeric", "skip", "skip", "numeric", 
        "skip", "skip", "numeric", "skip", 
        "skip", "skip"))

vul_raw <- read_excel("data/2021_01_06_Climate Vulnerability Composite Score_MASTER FILE.xlsx", 
    sheet = "Social Vulnerability", col_types = c("text", 
        "skip", "numeric", "skip", "skip", 
        "skip"))

bg_raw <- st_read("data/shape_files/tl_2019_48_bg.shp", stringsAsFactors = FALSE)
bg_raw <-st_transform(bg_raw,"+proj=longlat +ellps=WGS84 +datum=WGS84")
bg_raw$area <- st_area(bg_raw) |> set_units(mi^2)

ej_raw <- read_csv("data/EJSCREEN_2020_USPR.csv")

ej_columns_raw <- read_excel("data/2020_EJSCREEEN_columns-explained.xlsx", 
    col_types = c("skip", "text", "text"))

car_ownership_raw <- read_csv("data/ACSDT5Y2019.B25046_data_with_overlays_2021-05-14T114405.csv", 
    col_types = cols(NAME = col_skip(), B25046_001M = col_skip(), 
        B25046_002E = col_skip(), B25046_002M = col_skip(), 
        B25046_003E = col_skip(), B25046_003M = col_skip()))


car_perhousehold_raw <- read_csv("data/ACSDT5Y2019.B25044_data_with_overlays_2021-05-13T103710.csv", 
    col_types = cols(NAME = col_skip(), B25044_001M = col_skip(), 
        B25044_002M = col_skip(), B25044_003M = col_skip(), 
        B25044_004M = col_skip(), B25044_005M = col_skip(), 
        B25044_006M = col_skip(), B25044_007M = col_skip(), 
        B25044_008M = col_skip(), B25044_009M = col_skip(), 
        B25044_010M = col_skip(), B25044_011M = col_skip(), 
        B25044_012M = col_skip(), B25044_013M = col_skip(), 
        B25044_014M = col_skip(), B25044_015M = col_skip()))

caces_lur_raw <- read_csv("data/caces_lur_2015.csv")

caces_rcm_raw <- read_csv("data/caces_rcm_2017.csv")

BG_xwalk_raw <- read_csv("data/BG_xwalk.csv")

capcog_oz_raw <- st_read("data/shape_files/Ozone_Modeling_2020.shp") |> clean_names()
capcog_oz_raw  <-st_transform(capcog_oz_raw ,"+proj=longlat +ellps=WGS84 +datum=WGS84")

capcog_pm2.5_raw <- st_read("data/shape_files/Fine_Particulate_Matter_Modeling.shp") |> clean_names()
capcog_pm2.5_raw  <-st_transform(capcog_pm2.5_raw ,"+proj=longlat +ellps=WGS84 +datum=WGS84")

capcogcensus <- read_csv("data/ACSDT5Y2019.B01003_data_with_overlays_2021-08-02T184911.csv") |>
    row_to_names(row_number =1) |>
    clean_names() |> 
    mutate(id = str_sub(id, 10, -1)) |> 
    rename(population = estimate_total) |> 
    dplyr::select(-c(margin_of_error_total))
```



```{r carownership}

car <- car_ownership_raw

colnames(car) <- as.character(unlist(car[1,]))
car = car[-1, ]


car$id <- substring(car$id, 10)
car$`Estimate!!Aggregate number of vehicles available:`[car$`Estimate!!Aggregate number of vehicles available:` == "null"] <- 0
car$`Estimate!!Aggregate number of vehicles available:` <- as.numeric(car$`Estimate!!Aggregate number of vehicles available:`)
```

```{r carhousehold}

car_household <- car_perhousehold_raw
colnames(car_household) <- as.character(unlist(car_household[1,]))
car_household  = car_household[-1, ]
car_household$id <- substring(car_household$id, 10)
car_household$`Estimate!!Total:!!Owner occupied:!!No vehicle available` <- as.numeric(car_household$`Estimate!!Total:!!Owner occupied:!!No vehicle available`)
car_household$`Estimate!!Total:!!Renter occupied:!!No vehicle available` <- as.numeric(car_household$`Estimate!!Total:!!Renter occupied:!!No vehicle available`)
car_household$`Estimate!!Total:` <- as.numeric(car_household$`Estimate!!Total:`)
car_household$`No Car` <- car_household$`Estimate!!Total:!!Owner occupied:!!No vehicle available` + car_household$`Estimate!!Total:!!Renter occupied:!!No vehicle available`
car_household$`Percent of households without a car` <- car_household$`No Car`/car_household$`Estimate!!Total:`

car_household <- car_household |> dplyr::select(id,`Percent of households without a car` )

```


# Capcog data

```{r capcog}
cap_ozone <- capcog_oz_raw |> 
    dplyr::select(fid, fourth_hig, geometry) |> 
    mutate(var = "Ozone - CAPCOG",
           "Total population" = 100000,
           "% people of color" = 0.8,
           "% low-income" = 0.8,
           fid = as.character(fid)) |> 
    rename(GEOID_ = fid, value = fourth_hig)


cap_pm2.5 <- capcog_pm2.5_raw |> 
    dplyr::select(fid, b_pm25_ann, geometry) |> 
    mutate(var = "PM2.5 - CAPCOG",
           "Total population" = 100000,
           "% people of color" = 0.8,
           "% low-income" = 0.8,
           fid = as.character(fid)) |> 
    rename(GEOID_ = fid, value = b_pm25_ann)
    




```




```{r}

#Minor Cleaning
df_composite <- df_raw[1:640,]

df_composite$`SVI+Flood`[is.na(df_composite$`SVI+Flood`)] <- 0

ej_columns <- ej_columns_raw[-2,]

new_columns <- ej_columns$Description

ej <- ej_raw

colnames(ej) <- new_columns

ej$`Percentile for Ozone level in air` <-
    as.numeric(ej$`Percentile for Ozone level in air`)
ej$`Percentile for Ozone level in air` <-
    ej$`Percentile for Ozone level in air` * 0.01
ej$`Percentile for PM2.5 level in air` <-
    as.numeric(ej$`Percentile for PM2.5 level in air`)
ej$`Percentile for PM2.5 level in air` <-
    ej$`Percentile for PM2.5 level in air` * 0.01

lur <-
    caces_lur_raw |> dplyr::select(fips, pollutant, pred_wght) |> spread(pollutant, pred_wght)
lur$fips <- as.character(lur$fips)

rcm <- caces_rcm_raw |> filter(season == "fall") |>
    dplyr::select(fips, pollutant, damage) |>
    spread(pollutant, damage) |>
    rename(
        "NH3 Damage ($)" = "nh3",
        "NOx Damage ($)" = "nox",
        "PM25 Damage ($)" = "pm25",
        "SO2 Damage ($)"  = "so2"
    )
rcm$fips <- as.character(rcm$fips)

bg <- BG_xwalk_raw |> dplyr::select(GEOID,Avg_Imperv, Count, Count_Tree, Avg_Tree, Index)
bg$GEOID <- as.character(bg$GEOID)

#merging  
df <-
    capcogcensus |> 
    left_join(df_composite, by = c("id" = "GEOID_")) |>
    left_join(bg_raw, by = c("id" = "GEOID")) |>
    left_join(ej, by = c("id" = "Census FIPS code for block group")) |>
    left_join(exposure_raw, by = c("id" = "GEOID_")) |>
    left_join(vul_raw, by = c("id" = "ID_Blk_Grp")) |>
    left_join(car, by = "id") |>
    left_join(car_household, by = c("id" = "id")) |>
    left_join(lur, by = c("id" = "fips")) |>
    left_join(rcm, by = c("id" = "fips")) |>
    left_join(bg, by = c("id" = "GEOID")) |> 
    rename(
        "Multihazard Exposure" = "Norm_Composite (Norm)",
        "Social Vulnerability Score" = "SVI Score (0-1)",
        "Climate Exposure and Climate Vulnerability" = "Norm_COMPOSITE (v1)",
        "Aggregate Vehicles" = "Estimate!!Aggregate number of vehicles available:",
        "Wildfire Exposure" = "Wildfire Exposure (Norm)",
        "Heat Exposure" = "Heat Exposure (Norm",
        "Flood Exposure" = "Flood Exposure (norm)",
        "CO" = "co",
        "NO2" = "no2",
        "O3" = "o3",
        "PM10" = "pm10",
        "PM2.5" = "pm25",
        "SO2" = "so2",
        "Average Impervious Cover" = "Avg_Imperv",
        "Average Tree Cover" = "Avg_Tree",
        "Population" = "population"
    ) |>
    dplyr::select(
        id,
        "Wildfire Exposure",
        "Heat Exposure",
        "Flood Exposure",
        "Multihazard Exposure",
        "Social Vulnerability Score",
        "Climate Exposure and Climate Vulnerability",
        "Percentile for Ozone level in air" ,
        "Percentile for PM2.5 level in air",
        "Population",
        "% people of color",
        "% low-income",
        "% under age 5",
        "% over age 64",
        "Aggregate Vehicles",
        "Percent of households without a car",
        # "CO",
        # "NO2",
        # "SO2",
        # "O3",
        "PM10",
        "PM2.5",
        "Average Impervious Cover",
        "Average Tree Cover",
        "Shape area",
        "area",
        geometry
        
    )


df$Population <- as.numeric(df$Population)
df$`Average Vehicles per person` <-
    df$`Aggregate Vehicles` / df$`Population`

df <- df |> dplyr::select(-c("Aggregate Vehicles"))
df$`Average Vehicles per person`[df$`Average Vehicles per person` == 0] <-
    0.5

df$area <- as.numeric(df$area)

df$`Population Density` <-
    df$`Population` / df$`area` 
df$`Population Density`[df$`Population Density`== Inf] <- 1
df$`Population Density`[df$`Population Density`== 0] <- 1
df$`Log Population Density` <- log(df$`Population Density`)
#df$`Population Density`[df$`Population Density`== 0] <- 197


geometry <- dplyr::select(df,
                   id,
                   geometry,
                   "Population",
                   "% people of color",
                   "% low-income",)
df <-
    df |>
    dplyr::select(
        id,
        "Average Vehicles per person",
        "Percent of households without a car",
        "Population Density",
        "Log Population Density",#YOu need to add variables here if they are at the end
        everything()
    ) |>
    mutate(across(everything(), as.character)) |>
    pivot_longer(cols = 2:23, #This has to be adjusted when you add or remove variables 
                 names_to = "var",
                 values_to = "value") |>
    dplyr::select(id, var, value) |>
    left_join(geometry)



df$value <- as.numeric(df$value)

df$value[is.na(df$value)] <- 0

df$var[df$var == "Climate Exposure and Climate Vulnerability"] <-
    "Multihazard Exposure and Population Sensitivity"

df$var[df$var == "Social Vulnerability Score"] <-
    "Population Sensitivity"

#The airport is skewing the visualizations
df$value[df$var == "PM2.5" & df$value == 0] <- 8
df$value[df$var == "PM10" & df$value == 0] <- 22
# df$value[df$var == "CO" & df$value == 0] <- 0.2
# df$value[df$var == "NO2" & df$value == 0] <- 3
# df$value[df$var == "SO2" & df$value == 0] <- 0.9
# df$value[df$var == "O3" & df$value == 0] <- 43

df <- bind_rows(df, cap_ozone, cap_pm2.5)

saveRDS(df, "data/austin_composite.rds")

```


```{r asthma}
library(tidycensus)

asthma <- read_rds("data/asthma_prevalence_2017_capcog.rds") |> 
    mutate(child_prev = child_prev * 10000,
           adult_prev = adult_prev * 10000,
           total_prev = total_prev * 10000) |> 
    select(GEOID, child_prev, adult_prev, total_prev, geometry) |> 
    pivot_longer(cols = child_prev:total_prev,  
                 names_to = "var",
                 values_to = "value") 

#acs variables 
vars <- c("B02001_001", "B02001_002", "B06012_002", "B06012_003" )

#enter your key census_api_key("Your key here")
acs <- x <-get_acs(state="TX", geography="tract",year = 2017, variables=vars, geometry=FALSE)

acs2 <- acs |> 
    pivot_wider(names_from = variable, values_from = c(estimate, moe)) |> 
    rename("Population" = estimate_B02001_001,
           "white" = estimate_B02001_002,
           "below_poverty" = estimate_B06012_002,
           "between_poverty" = estimate_B06012_003) |>
    mutate("% people of color" = (Population-white)/Population,
           "% low-income" = (below_poverty + between_poverty)/Population) |> 
    select(GEOID, Population, "% people of color", "% low-income")

asthma <- asthma |> 
    left_join(acs2, by = "GEOID")


asthma <- st_as_sf(asthma) |> 
  st_transform("+proj=longlat +ellps=WGS84 +datum=WGS84")

saveRDS(asthma, "data/asthma_for_app.rds")
```

